from enum import Enum


class FSMState(str, Enum):
    S0_START = "S0_START"
    S1_SCHEMA_KNOWN = "S1_SCHEMA_KNOWN"
    S2_SURFACE_MAPPED = "S2_SURFACE_MAPPED"
    S3_AUTH_CONTEXT_AVAILABLE = "S3_AUTH_CONTEXT_AVAILABLE"
    S4_OPERATION_SELECTED = "S4_OPERATION_SELECTED"
    S5_INPUT_SPACE_PREPARED = "S5_INPUT_SPACE_PREPARED"
    S6_REQUEST_EXECUTED = "S6_REQUEST_EXECUTED"
    S7_RESPONSE_CLASSIFIED = "S7_RESPONSE_CLASSIFIED"
    S8_INTERESTING_BEHAVIOR_FOUND = "S8_INTERESTING_BEHAVIOR_FOUND"
    S9_REPRODUCIBLE_FINDING = "S9_REPRODUCIBLE_FINDING"
    S10_MUTATION_PLANNED = "S10_MUTATION_PLANNED"
    S11_RESET = "S11_RESET"
